transcript on
if {[file exists rtl_work]} {
	vdel -lib rtl_work -all
}
vlib rtl_work
vmap work rtl_work

vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/user_ram.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/SMcomparator.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/Single_Cycle.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/register_file.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/program_counter.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/PC_incremented.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/Output_Periph.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/MUX3_1.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/MUX2_1.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/LU_32bit.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/LU_1bit.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/LSU.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/LED.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/LCD.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/Input_Periph.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/Immediate_generator.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/HEX.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/FA_32bit.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/FA_1bit.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/dff_user.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/Data_memory.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/ControlUnit.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/clock_divider.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/CLA_16bit.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/CLA_4bit.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/brcomp.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/barrel_shifter_right_32.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/barrel_shifter_left_32.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/barrel_shifter_32.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/AU.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/ALU_Control.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/ALU.sv}
vlog -sv -work work +incdir+C:/Users/Duc/A\ PLACE\ HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src {C:/Users/Duc/A PLACE HOLDER/University/Computer_Organization/project/RISCV/Single_Cycle_New_Mapping/src/Instruction_Memory.sv}

